# Generated by Django 6.0.1 on 2026-09-21 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('shield', 'Escudo'), ('alert', 'Escudo con alerta'), ('bell', 'Campana / alerta'), ('pin', 'Ubicacion'), ('users', 'Comunidad'), ('truck', 'Vehiculo / flota'), ('activity', 'Telemetria'), ('chart', 'Estadisticas'), ('phone', 'Aplicacion movil'), ('clock', 'Tiempo real / 24-7'), ('report', 'Reportes'), ('map', 'Rastreo / mapa'), ('building', 'Entidad / empresa'), ('radio', 'Boton fisico / transmision'), ('check', 'Verificado'), ('lock', 'Seguridad / privacidad'), ('headset', 'Central de monitoreo')], default='shield', max_length=30, verbose_name='Icono')),
                ('audience', models.CharField(choices=[('app', 'App movil (usuarios finales)'), ('panel', 'Panel administrativo (entidades)')], default='app', max_length=20, verbose_name='Seccion')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('image', models.ImageField(blank=True, help_text='Opcional. Recomendado 1200x900 px (4:3). Si la dejas vacia se muestra el icono.', null=True, upload_to='features/', verbose_name='Imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Funcionalidad',
                'verbose_name_plural': 'Funcionalidades',
                'ordering': ['audience', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=255, verbose_name='Ruta')),
                ('visitor_key', models.CharField(db_index=True, help_text='Hash de la sesion (o de IP + navegador). No guarda datos identificables.', max_length=64, verbose_name='Visitante')),
                ('referer', models.CharField(blank=True, max_length=500, verbose_name='Origen')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='Navegador')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('audience', models.CharField(choices=[('personas', 'Personas y familias'), ('empresas', 'Entidades de seguridad')], default='personas', max_length=20, verbose_name='Publico')),
                ('tagline', models.CharField(blank=True, help_text='Una linea que resuma para quien es el plan.', max_length=140, verbose_name='Frase corta')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Opcional. Hoy el sitio no muestra precios; se guarda para mas adelante.', max_digits=10, null=True, verbose_name='Precio')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Moneda')),
                ('billing_period', models.CharField(choices=[('mensual', 'Mensual'), ('anual', 'Anual'), ('unico', 'Pago unico'), ('personalizado', 'Personalizado')], default='mensual', max_length=20, verbose_name='Periodo')),
                ('show_price', models.BooleanField(default=False, help_text="Actualmente el sitio muestra 'Cotizar'. Activalo cuando quieras publicar el precio.", verbose_name='Mostrar precio en el sitio')),
                ('image', models.ImageField(blank=True, help_text='Opcional. Recomendado 800x600 px (4:3), JPG o PNG.', null=True, upload_to='planes/', verbose_name='Imagen')),
                ('badge', models.CharField(blank=True, help_text="Ej: 'Mas elegido'. Se muestra sobre la tarjeta.", max_length=30, verbose_name='Etiqueta')),
                ('whatsapp_message', models.CharField(blank=True, help_text='Opcional. Si lo dejas vacio se usa el mensaje por defecto con el nombre del plan.', max_length=200, verbose_name='Mensaje de WhatsApp')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['audience', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140, verbose_name='Caracteristica')),
                ('is_included', models.BooleanField(default=True, help_text='Si la desmarcas se muestra tachada, util para comparar planes.', verbose_name='Incluida')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='marketing.plan')),
            ],
            options={
                'verbose_name': 'Caracteristica del plan',
                'verbose_name_plural': 'Caracteristicas del plan',
                'ordering': ['order', 'id'],
            },
        ),
    ]
