# Generated by Django 6.0.1 on 2026-09-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_contenido_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('panel', 'Captura del panel administrativo'), ('logo', 'Logo de la marca'), ('og', 'Imagen para redes sociales')], help_text='Donde se muestra la imagen. Solo puede haber una por ubicacion.', max_length=20, unique=True, verbose_name='Ubicacion')),
                ('image', models.ImageField(help_text='Medidas recomendadas: panel 1600x1000 px, logo 512x512 px (fondo transparente), redes sociales 1200x630 px.', upload_to='sitio/', verbose_name='Imagen')),
                ('alt_text', models.CharField(blank=True, help_text='Descripcion breve para lectores de pantalla y buscadores.', max_length=200, verbose_name='Texto alternativo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
            ],
            options={
                'verbose_name': 'Imagen del sitio',
                'verbose_name_plural': 'Imagenes del sitio',
                'ordering': ['slot'],
            },
        ),
    ]
